steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
      - '-t'
      - 'africa-south1-docker.pkg.dev/$PROJECT_ID/sensa-ai-repo/sensa-ai-frontend:$BUILD_ID'
      - '.'
      - '-f'
      - Dockerfile
    id: Build

  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'africa-south1-docker.pkg.dev/$PROJECT_ID/sensa-ai-repo/sensa-ai-frontend:$BUILD_ID'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sensa-ai-frontend'
      - '--image'
      - 'africa-south1-docker.pkg.dev/$PROJECT_ID/sensa-ai-repo/sensa-ai-frontend:$BUILD_ID'
      - '--region'
      - 'africa-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-env-vars=VITE_SUPABASE_URL=$_VITE_SUPABASE_URL,VITE_SUPABASE_ANON_KEY=$_VITE_SUPABASE_ANON_KEY'
      # The VITE_ variables are build-time arguments and must be passed to the Docker build.
      # Cloud Run doesn't directly support passing --build-arg, so we rely on them being
      # present in the environment where `gcloud builds submit` is run.
      # For Cloud Run runtime, you'd use --set-env-vars. Since Vite bakes these into static files,
      # they are not needed at runtime.

# Store the image in Artifact Registry
images:
  - 'africa-south1-docker.pkg.dev/$PROJECT_ID/sensa-ai-repo/sensa-ai-frontend:$BUILD_ID'

# Build options - using a more standard machine type
options:
  machineType: 'E2_MEDIUM'

# Timeout for the build
timeout: '1600s' 