steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Build the application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/sensa-ai:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/sensa-ai:latest',
      '.'
    ]

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sensa-ai:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sensa-ai:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'sensa-ai',
      '--image', 'gcr.io/$PROJECT_ID/sensa-ai:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '80',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--set-env-vars', 'NODE_ENV=production'
    ]

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/sensa-ai:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sensa-ai:latest'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'

# Timeout
timeout: '1200s' 